[package]
name = "langbeam"
version = "0.1.2"
edition = "2021"
description = "Rainbeam language file manager"
authors = ["trisuaso", "swmff"]
homepage = "https://rainbeam.net"
repository = "https://github.com/swmff/rainbeam"
license = "MIT"

[dependencies]
serde = { version = "1.0.216", features = ["serde_derive"] }
serde_json = "1.0.134"
rainbeam-shared = "0.2.0"
pathbufd = "0.1.3"
